### ISSUE TITLE
Hombrew install via basics.sh fails  

### ISSUE THREAD

**Issue by csut-dev** [anmut-consulting/pipenv-cookiecutter#32]
Currently, there is an issue with the basics.sh script that causes Homebrew (the package manager) to install incorrectly on certain machines. This could be an issue with an out of date install script. 

This issue can be bypassed by running basics.sh until the installation of Homebrew fails (which is signified by the error `brew is not in path`, installing brew via https://brew.sh/ and following the on-screen instructions (making sure to add the script to path) and then finally re-running basics.sh.

**Comment by stefan-anmut** [comment]
updated according to suggestion in the following link: https://brew.sh
